---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apps.tonygilkerson.com
spec:
  group: tonygilkerson.com
  names:
    kind: App
    plural: apps
    singular: app
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              image:
                type: string
              port:
                type: integer
              cpuLimit:
                type: string
              memLimit:
                type: string
              cpuReq:
                type: string
              memReq:
                type: string
              host:
                type: string
              replicas:
                type: integer
                default: 1
            required:
            - image
            - host
    subresources:
     status: {}

---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: slacks.tonygilkerson.com
spec:
  group: tonygilkerson.com
  names:
    kind: Slack
    plural: slacks
    singular: slack
    shortNames:
    - sl
  scope: Cluster
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
    subresources:
     status: {}
