apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: basic-app
spec:
  generateSelector: true
  parentResource:
    apiVersion: tonygilkerson.com/v1
    resource: basicapps
  childResources:
  - apiVersion: apps/v1
    resource: deployments
    updateStrategy:
      method: InPlace
  - apiVersion: v1
    resource: services
    updateStrategy:
      method: InPlace
  - apiVersion: networking.k8s.io/v1
    resource: ingresses
    updateStrategy:
      method: InPlace
  hooks:
    sync:
      webhook:
        url: http://basic-app.controllers/sync