apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: basicapps.tonygilkerson.com
spec:
  group: tonygilkerson.com
  names:
    kind: BasicApp
    plural: basicapps
    singular: basicapp
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              portfolio:
                type: string
              image:
                type: string
              host:
                type: string
              port:
                type: integer
            required:
            - image
            - host
            - portfolio
    subresources:
     status: {}